# Generated by Django 5.2 on 2025-04-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_reading_lists', to='book.book'),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to='account.customuser'),
        ),
        migrations.AlterUniqueTogether(
            name='readinglist',
            unique_together={('user', 'book')},
        ),
    ]
