# Generated by Django 5.2 on 2025-04-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('group_membership', '0003_alter_groupmembership_user'),
        ('task_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='account.customuser'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='members',
            field=models.ManyToManyField(related_name='task_groups', through='group_membership.GroupMembership', to='account.customuser'),
        ),
    ]
